#version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: cloud/docker/Dockerfile-cloud-backend
    container_name: codexion-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
      - "22:22"
    volumes:
      - ./cloud/backend:/workspace
    tty: true
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: cloud/docker/Dockerfile-cloud-frontend
    container_name: codexion-frontend
    volumes:
      - ./cloud/frontend/react:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://codexion-backend:8000
    command: npm run dev
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"

  nginx:
    image: nginx:1.25
    container_name: codexion-nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./cloud/docker/cloud-nginx.conf:/etc/nginx/cloud-nginx.conf:ro
      - ./cloud/frontend/react/dist:/usr/share/nginx/html:ro
    ports:
      - "${NGINX_PORT:-80}:80"
    restart: unless-stopped
