services:
  erp_techmedia_co_in:
    image: codexion-cloud:v1
    container_name: erp_techmedia_co_in
    ports:
      - "8001:8000"
    volumes:
      - ./public/erp_techmedia_co_in:/home/devops/shared
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true