services:
  smile_codexsun_com:
    image: codexion-cloud:v1
    container_name: smile_codexsun_com
    ports:
      - "8004:8000"
    volumes:
      - ./public/smile_codexsun_com:/home/devops/shared
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true