# -------------------------
# Base Image
# -------------------------
FROM ubuntu:24.04

LABEL maintainer="codexion"
LABEL author="Sundar <sundar@sundar.com>"
LABEL version="1.0"
LABEL description="Codexion - Frappe-ready image with Gunicorn and Supervisor"

# -------------------------
# Environment Setup
# -------------------------
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV PYENV_ROOT="/home/devops/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
ENV NVM_DIR="/home/devops/.nvm"
ENV NODE_VERSION=20.19.2

# -------------------------
# Install System Dependencies
# -------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential curl wget git unzip sudo ca-certificates gnupg2 \
  software-properties-common locales lsb-release \
  mariadb-client libmariadb-dev \
  redis-server redis-tools \
  libssl-dev libffi-dev libpq-dev libldap2-dev libsasl2-dev \
  zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
  libncursesw5-dev xz-utils tk-dev liblzma-dev \
  python3.12 python3.12-dev python3.12-venv python3-pip \
  supervisor \
  && ln -sf /usr/bin/python3.12 /usr/bin/python3 \
  && ln -sf /usr/bin/pip3 /usr/bin/pip \
  && locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8 \
  && mkdir -p /var/run/sshd \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------
# Install wkhtmltopdf 0.12.6.1
# -------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
  libjpeg-turbo8 libxrender1 xfonts-base xfonts-75dpi && \
  cd /tmp && \
  wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb && \
  apt-get install -y ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb && \
  rm -f ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

# -------------------------
# Create DevOps User
# -------------------------
RUN groupadd devops && \
    useradd -m -g devops -s /bin/bash devops && \
    echo 'devops ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# -------------------------
# Switch to devops
# -------------------------
USER devops
WORKDIR /home/devops

# -------------------------
# Install pyenv + Python 3.12.3
# -------------------------
RUN git clone https://github.com/pyenv/pyenv.git "$PYENV_ROOT" && \
    git clone https://github.com/pyenv/pyenv-virtualenv.git "$PYENV_ROOT/plugins/pyenv-virtualenv" && \
    $PYENV_ROOT/bin/pyenv install 3.12.3 && \
    $PYENV_ROOT/bin/pyenv global 3.12.3 && \
    $PYENV_ROOT/versions/3.12.3/bin/pip install --upgrade pip setuptools wheel && \
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc && \
    echo 'export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"' >> ~/.bashrc && \
    echo 'eval "$(pyenv init --path)"' >> ~/.bashrc && \
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc

# -------------------------
# Install Node.js + Yarn via NVM
# -------------------------
RUN mkdir -p "$NVM_DIR" && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash && \
    export NVM_DIR="$NVM_DIR" && \
    . "$NVM_DIR/nvm.sh" && \
    nvm install $NODE_VERSION && \
    nvm use $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    npm install -g yarn

# -------------------------
# Persist NVM globally (after root switch)
# -------------------------
USER root
RUN echo "export NVM_DIR=\"$NVM_DIR\"" > /etc/profile.d/nvm.sh && \
    echo "[ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"" >> /etc/profile.d/nvm.sh && \
    echo "export PATH=\"\$NVM_DIR/versions/node/v$NODE_VERSION/bin:\$PATH\"" >> /etc/profile.d/nvm.sh && \
    chmod +x /etc/profile.d/nvm.sh

# -------------------------
# Install Bench CLI
# -------------------------
USER devops
RUN git clone --depth 1 -b v5.x https://github.com/frappe/bench ~/.bench && \
    $PYENV_ROOT/shims/pip install --user -e ~/.bench && \
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc && \
    echo 'export BENCH_DEVELOPER=1' >> ~/.bashrc

# -------------------------
# Symlink bench CLI globally
# -------------------------
USER root
RUN ln -sf /home/devops/.local/bin/bench /usr/local/bin/bench

# -------------------------
# CLI Script for DevOps
# -------------------------
COPY ./cloud/frappe/init_frappe.sh /usr/local/bin/ifrappe
COPY ./cloud/frappe/dbsetup.sh /usr/local/bin/idbsetup
RUN chmod +x /usr/local/bin/ifrappe
RUN chmod +x /usr/local/bin/idbsetup

# -------------------------
# Install Gunicorn for Frappe Web Serving
# -------------------------
RUN pip install gunicorn

# -------------------------
# Copy Supervisor Configuration
# -------------------------
COPY ./cloud/frappe/supervisord.conf /etc/supervisor/supervisord.conf

# -------------------------
# Supervisor Log Folder
# -------------------------
RUN mkdir -p /home/devops/logs
RUN mkdir -p /var/log/supervisor && chown -R devops:devops /var/log/supervisor

# -------------------------
# Expose Required Ports
# -------------------------
EXPOSE 8000 9000 3306 6379

# -------------------------
# Launch Supervisor on container start
# -------------------------
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

# -------------------------
# Set Default Shell
# -------------------------
SHELL ["/bin/bash", "-c"]
