[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
logfile=/home/devops/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=true
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:frappe-web]
command=/home/devops/.pyenv/versions/3.12.3/bin/gunicorn -b 0.0.0.0:8000 frappe.app:application --workers=4
directory=/home/devops/frappe-bench/sites
autostart=true
autorestart=true
user=devops
stdout_logfile=/var/log/supervisor/frappe-web.log
stderr_logfile=/var/log/supervisor/frappe-web.err

[program:frappe-worker]
command=/home/devops/.local/bin/bench worker
directory=/home/devops/frappe-bench
autostart=true
autorestart=true
user=devops
stdout_logfile=/var/log/supervisor/frappe-worker.log
stderr_logfile=/var/log/supervisor/frappe-worker.err

[program:frappe-scheduler]
command=/home/devops/.local/bin/bench schedule
directory=/home/devops/frappe-bench
autostart=true
autorestart=true
user=devops
stdout_logfile=/var/log/supervisor/frappe-scheduler.log
stderr_logfile=/var/log/supervisor/frappe-scheduler.err
