[supervisord]
logfile=/home/devops/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=5
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=false
childlogdir=/home/devops/logs
minfds=1024
minprocs=200

[include]
files = /etc/supervisor/conf.d/*.conf

[program:frappe]
directory=/home/devops/frappe-bench
command=/home/devops/frappe-bench/env/bin/bench start
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/frappe_stdout.log
stderr_logfile=/var/log/supervisor/frappe_stderr.log
user=devops
