services:
  dev_aaranerp_com:
    image: codexion-cloud:v1
    container_name: dev_aaranerp_com
    ports:
      - "8007:8000"
    volumes:
      - ./public/dev_aaranerp_com:/home/devops/shared
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true