services:
  site1_com:
    build:
      context: .
      dockerfile: Dockerfile
    image: site1_com:v1
    container_name: site1_com
    ports:
      - "8000:8000"
    volumes:
      - ./public/site1_com:/app/public
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true
