services:
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "DbPass1@@"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    networks:
      - codexion-network

volumes:
  mariadb_data:

networks:
  codexion-network:
    external: true
