# Dockerfile

FROM ubuntu:24.04

LABEL maintainer="SUNDAR"

# Set non-interactive frontend for apt
ENV DEBIAN_FRONTEND=noninteractive

# Set working directory
WORKDIR /workspace

# Install base development packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.12 python3.12-venv python3.12-dev python3-pip \
    openssh-server sudo \
    curl wget git nano unzip ca-certificates \
    build-essential libssl-dev libffi-dev libpq-dev \
    libmariadb-dev libsqlite3-dev zlib1g-dev \
    && ln -sf /usr/bin/python3.12 /usr/bin/python3 \
    && ln -sf /usr/bin/pip3 /usr/bin/pip \
    && mkdir -p /var/run/sshd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy backend source code
COPY ./cloud/backend/ /workspace

# Copy CLI and make global
COPY ./cloud/backend/setup/init.sh /usr/local/bin/codexion
RUN chmod +x /usr/local/bin/codexion


# Create user sundar with home directory
RUN useradd -m -d /home/sundar -s /bin/bash sundar && \
    echo "sundar:sundar" | chpasswd && \
    mkdir -p /home/sundar/workspace && \
    chown -R sundar:sundar /home/sundar && \
    chmod 755 /home/sundar

# Optional: mount workspace directory
RUN mkdir -p /workspace && ln -s /workspace /home/sundar/workspace

# Expose SSH port for SFTP
EXPOSE 22

# Start SSH daemon
SHELL ["/bin/bash", "-c"]

